language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  - ENABLE_DEBUG=no
  - ENABLE_DEBUG=yes

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get -qq install build-essential libpng-dev libjpeg-dev libavformat-dev libavcodec-dev libavutil-dev libswscale-dev

script:
  - ./autogen.sh
  - ./configure --enable-silent-rules --enable-unit-tests --enable-debug=$ENABLE_DEBUG
  - make -j4
  - make -j4 check
